# Generated by Django 3.0.7 on 2021-04-06 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('taught_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'professor'}, null=True, on_delete=django.db.models.fields.Empty, related_name='taught_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_material.Course')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'professor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lesson_id'],
            },
        ),
        migrations.CreateModel(
            name='EnrollStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_material.Course')),
                ('student_id', models.ForeignKey(limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
