# Generated by Django 3.0.7 on 2021-03-05 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_material', '0002_auto_20210305_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='taught_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'professor'}, null=True, on_delete=django.db.models.fields.Empty, related_name='taught_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
