# Generated by Django 3.0.7 on 2021-03-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0004_enrollstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
