# Generated by Django 3.0.7 on 2021-03-12 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0005_testtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtime',
            name='name',
        ),
        migrations.AddField(
            model_name='testtime',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
