# Generated by Django 3.0.7 on 2021-03-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0007_auto_20210312_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTime',
        ),
    ]
