# Generated by Django 3.0.7 on 2021-03-16 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0010_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 0, 23, 50, 454263, tzinfo=utc)),
        ),
    ]
