# Generated by Django 3.0.7 on 2021-03-16 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0013_auto_20210316_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 13, 23, 40, 769463, tzinfo=utc)),
        ),
    ]
