# Generated by Django 3.0.7 on 2021-03-18 00:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0014_auto_20210316_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 0, 29, 47, 284933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enrollstudent',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_material.Course'),
        ),
    ]
