# Generated by Django 3.0.7 on 2021-03-22 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0015_auto_20210318_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 22, 9, 55, 19, 312832, tzinfo=utc)),
        ),
    ]
