# Generated by Django 3.0.7 on 2021-03-23 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0016_auto_20210322_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 23, 15, 33, 24, 881982, tzinfo=utc)),
        ),
    ]
