# Generated by Django 3.0.7 on 2021-03-24 01:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0024_auto_20210323_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 1, 34, 19, 591798, tzinfo=utc)),
        ),
    ]
