# Generated by Django 3.0.7 on 2021-03-24 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0025_auto_20210324_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTime',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
