# Generated by Django 3.0.7 on 2021-03-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_material', '0026_auto_20210324_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='learning_material.Course'),
        ),
    ]
