# Generated by Django 3.0.7 on 2021-03-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210302_0148'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
    ]
