# Generated by Django 3.0.7 on 2021-03-22 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='name',
        ),
        migrations.AddField(
            model_name='test',
            name='my_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
