# Generated by Django 3.0.7 on 2021-03-23 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20210322_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserProfile',
        ),
    ]
